### ISSUE TITLE
Request: airports and waypoints from europe

### ISSUE THREAD

**Issue by OdomLinx** [mrieker/HSIWatch#1]
HI,

Hello,

Is it possible to integrate the airports, VOR etc. of Europe?
Data would be available e.g. here www.openflightmaps.org/.

For each country these data are available in the following formats:
OFMX
ARINC424
OPENAIR

Thanks in advance

**Comment by mrieker** [comment]
k I put in waypoints from ourairports.com but can check out that other source

**Comment by OdomLinx** [comment]
Thx for adding ourairports.com,it works.
